### ISSUE TITLE
Rails 3?

### ISSUE THREAD

**Issue by lwille** [drnic/dr-nic-magic-models#1]
Is this project still active? Anything new about Rails 3 Support?

**Comment by drnic** [comment]
I hadn't really thought about it but perhaps I could. That'd be fun.

**Comment by andreydjason** [comment]
Could be very nice if it was compatible with Rails 3 and maybe an study to make some implementations (could use examples from RedBeanPHP - 'on-the-fly ORM'), that is in the same ideia this project was originally, but with more implementations, etc. If I could help in any case, please let me know, this could be a very interesting gem to use in some projects, if well designed for Rails 3.x.

**Comment by fiid** [comment]
I think magic models would solve a big problem for us.  Any sense of what it would take to make it work on rails 3?  Do you think it would be a big undertaking?
